### ISSUE TITLE
Mouse-wheel Zoom

### ISSUE THREAD

**Issue by acornforth** [linuxmint/pix#49] opened 2018-03-22 12:37 UTC
```
 * Pix version (1.6.2)
 * Distribution - (Mint 18.3 x64 Cinnamon)
```

**Issue**
mouse-wheel acts as zoom without any modifiers, this is inconsistent with the majority of other apps where ctrl+mouse-wheel is zoom, mouse-wheel-only is vertical scroll, and shift+mouse-wheel is horizontal scroll.

**Steps to reproduce**
use mousewheel in app

**Expected behaviour**
I would like to see the following either as default behaviour, or as an optional configuration:
mouse-wheel = v-scroll
shift+mouse-wheel = h-scroll
ctrl+mouse-wheel = zoom

**Other information**

**Comment by acornforth** [comment] 2018-03-22 12:40
See also #34 + comments on using ctrl+mousewheel for navigation!!!

**Comment by leigh123linux** [comment] 2018-03-22 12:56
Duplicate of  #34

**Closed** 2018-03-22 12:56 UTC
